### ISSUE TITLE
Inclusion of GPL 3.0 code

### ISSUE THREAD

**Issue by junekiwi** [anisayari/easy_intruder_detection#1]
Hi,

It seems that you include GPL 3.0 licensed code in your project (https://github.com/ultralytics/yolov3).

As per the copy left requirement of the license, you should distribute your project under this license (and not MIT).

See https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-

**Comment by anisayari** [comment]
Done thanks for notice. I updated the README as well with reference.
